# Generated by Django 4.0.6 on 2022-07-27 05:32

import artists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artistic_kinship',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='facebook',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='artist',
            name='groups_affiliation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='instagram',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, upload_to=artists.models.artist_directory_path),
        ),
        migrations.AlterField(
            model_name='artist',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='artist',
            name='website',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='artist',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='artist',
            name='works',
            field=models.TextField(blank=True),
        ),
    ]
