# Generated by Django 4.0.6 on 2022-07-28 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_alter_artist_artistic_kinship_alter_artist_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('slug', models.SlugField(max_length=60)),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='artists.category')),
            ],
            options={
                'unique_together': {('slug', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='categories',
            field=models.ManyToManyField(blank=True, to='artists.category'),
        ),
    ]
