# Generated by Django 4.1 on 2022-09-11 05:27

import artists.fields
import artists.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Artist', 'verbose_name_plural': 'Artists'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='artist',
            name='artistic_kinship',
            field=models.TextField(blank=True, verbose_name='Artistic Kinship'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='biography',
            field=models.TextField(verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='birth_city',
            field=models.CharField(max_length=120, verbose_name='Birth city'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='birth_date',
            field=models.DateField(verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='categories',
            field=models.ManyToManyField(blank=True, to='artists.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='facebook',
            field=models.CharField(blank=True, max_length=60, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='featured',
            field=models.BooleanField(verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='groups_affiliation',
            field=models.TextField(blank=True, verbose_name='Groups Affiliation'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='instagram',
            field=models.CharField(blank=True, max_length=60, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, upload_to=artists.models.artist_directory_path, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='related',
            field=models.ManyToManyField(blank=True, to='artists.artist', verbose_name='Related'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='views',
            field=models.IntegerField(default=0, editable=False, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='website',
            field=models.CharField(blank=True, max_length=120, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=60, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='works',
            field=models.TextField(blank=True, verbose_name='Works'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artists.category', verbose_name='Parent category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=60, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artist', verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='upload',
            field=artists.fields.PortfolioUploadField(blank=True, null=True, upload_to=artists.models.artist_directory_path, verbose_name='Upload'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='upload_type',
            field=models.CharField(choices=[('music', 'Music'), ('drawing', 'Drawing'), ('photo', 'Photo'), ('video', 'Video')], max_length=10, verbose_name='Upload type'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='views',
            field=models.IntegerField(default=0, editable=False, verbose_name='Views'),
        ),
    ]
