# Generated by Django 4.1 on 2022-09-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_alter_artist_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='original_slug',
            field=models.SlugField(default='', max_length=120, unique=True, verbose_name='Original Slug'),
        ),
    ]
