# Generated by Django 4.1.3 on 2022-12-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0012_category_past_slugs_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo_thumbnails',
            field=models.JSONField(default=dict, verbose_name='Photo thumbnails'),
        ),
    ]
