# Generated by Django 4.1.3 on 2022-12-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0013_artist_photo_thumbnails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='photo_thumbnails',
        ),
        migrations.AddField(
            model_name='artist',
            name='images_thumbnails',
            field=models.JSONField(default=dict, verbose_name='Images thumbnails'),
        ),
    ]
