# Generated by Django 4.1.3 on 2022-12-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0014_remove_artist_photo_thumbnails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
    ]
