version: "3.9"
   
services:
  db:
    deploy:
      replicas: 0
  web:
    command: prod
    working_dir: /code/
    entrypoint: /code/deployments/django/entrypoint.sh
    restart: always
    ports:
      - 127.0.0.1:5001:8000
    logging:
      driver: "json-file"
      options:
        labels: "app_name"
    labels:
      app_name: ${APP_NAME:-artists-catalog}
