version: "3.9"
   
services:
  db:
    image: mysql:5
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_HOST=%
  web:
    build:
      dockerfile: deployments/django/Dockerfile
      context: ../
    command: dev
    volumes:
      - ../:/code
    ports:
      - "5001:8000"
    environment:
      # - DJANGO_SETTINGS_MODULE="artistscatalog.settings"
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
      - AWS_LOCATION
    depends_on:
      - db
