version: "3.9"
   
services:
  db:
    deploy:
      replicas: 0
  web:
    command: prod
    working_dir: /code/
    entrypoint: /code/deployments/django/entrypoint.sh
    ports:
      - 127.0.0.1:5001:8000
    restart: always
