version: "3.9"
   
services:
  db:
    platform: linux/x86_64
    image: mysql:5
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_HOST=%
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 4
  web:
    build:
      dockerfile: deployments/django/Dockerfile
      context: ../
    working_dir: /code/
    entrypoint: /code/deployments/django/entrypoint.sh
    volumes:
      - ../:/code
      - ./data/home:/home/django
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
      - AWS_LOCATION
      - DEBUG
