version: "3.9"
   
services:
  web:
    ports:
      - 8002:8002
    command: dev
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    # network_mode: "host"
