# Generated by Django 4.1.1 on 2022-11-05 16:36

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('past_slugs', models.JSONField(default=list, verbose_name='Past Slugs')),
                ('link', models.URLField(blank=True, max_length=120, verbose_name='Website')),
                ('image', models.ImageField(blank=True, upload_to=news.models.news_directory_path, verbose_name='Image')),
                ('featured', models.BooleanField(verbose_name='Featured')),
                ('views', models.IntegerField(default=0, editable=False, verbose_name='Views')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
