# Generated by Django 4.1.1 on 2022-11-06 05:47

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='featured',
            field=models.BooleanField(default=True, verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=news.models.news_directory_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='link',
            field=models.URLField(max_length=120, verbose_name='Hyperlink'),
        ),
    ]
